
CSR1000V-IOS-XE-1: 
   ip: 192.168.1.231/24
   role: ios
   groups:
      - csr1000v

CSR1000V-IOS-XE-2: 
   ip: 192.168.1.232/24
   role: ios
   groups:
      - csr1000v

CSR1000V-IOS-XE-3: 
   ip: 192.168.1.233/24
   role: ios
   groups:
      - csr1000v

R1: 
   ip: 192.168.1.221/24
   role: ios
   groups:
      - 7200

R2: 
   ip: 192.168.1.222/24
   role: ios
   groups:
      - 7200

R3: 
   ip: 192.168.1.223/24
   role: ios
   groups:
      - 7200

R4: 
   ip: 192.168.1.224/24
   role: ios
   groups:
      - 7200
