
CSR1000V-IOS-XE-1:
    hostname: 192.168.10.231
    platform: 'ios'
    username: admin
    password: cisco
    groups:
        - csr1000v
    

CSR1000V-IOS-XE-2:
    hostname: 192.168.10.232
    platform: 'ios'
    username: admin
    password: cisco
    groups:
        - csr1000v
    

P-1:
    hostname: 192.168.10.223
    platform: 'ios'
    username: admin
    password: cisco
    groups:
        - 7200
    

P-2:
    hostname: 192.168.10.224
    platform: 'ios'
    username: admin
    password: cisco
    groups:
        - 7200
    

CE-1:
    hostname: 192.168.10.221
    platform: 'ios'
    username: admin
    password: cisco
    groups:
        - 7200
    

PE-1:
    hostname: 192.168.10.222
    platform: 'ios'
    username: admin
    password: cisco
    groups:
        - 7200
    

PE-2:
    hostname: 192.168.10.225
    platform: 'ios'
    username: admin
    password: cisco
    groups:
        - 7200
    

CE-2:
    hostname: 192.168.10.226
    platform: 'ios'
    username: admin
    password: cisco
    groups:
        - 7200
    
