---
R1:
    hostname: 192.168.1.221
    platform: 'ios'
    username: admin
    password: cisco
    groups:
        - cisco

R2:
    hostname: 192.168.1.222
    platform: 'ios'
    username: admin
    password: cisco
    groups:
        - cisco

R3:
    hostname: 192.168.1.223
    platform: 'ios'
    username: admin
    password: cisco
    groups:
        - cisco


R4:
    hostname: 192.168.1.224
    platform: 'ios'
    username: admin
    password: cisco
    groups:
        - cisco


CSR1000V-IOS-XE-1:
    hostname: 192.168.1.231
    platform: 'ios'
    username: admin
    password: cisco123
    groups:
        - csr1000v


CSR1000V-IOS-XE-2:
    hostname: 192.168.1.232
    platform: 'ios'
    username: admin
    password: cisco123
    groups:
        - csr1000v


CSR1000V-IOS-XE-3:
    hostname: 192.168.1.233
    platform: 'ios'
    username: admin
    password: cisco123
    groups:
        - csr1000v


cisshgo1000v-1:
    hostname: 192.168.1.225
    platform: 'ios'
    username: admin
    password: admin
    port: '10049'
    groups:
            - cissh
cisshgo1000v-2:
    hostname: 192.168.1.225
    platform: 'ios'
    username: admin
    password: admin
    port: '10000'
    groups:
            - cissh

cisshgo1000v-3:
    hostname: 192.168.1.225
    platform: 'ios'
    username: admin
    password: admin
    port: '10001'
    groups:
            - cissh

cisshgo1000v-4:
    hostname: 192.168.1.225
    platform: 'ios'
    username: admin
    password: admin
    port: '10002'
    groups:
            - cissh

cisshgo1000v-5:
    hostname: 192.168.1.225
    platform: 'ios'
    username: admin
    password: admin
    port: '10003'
    groups:
            - cissh

cisshgo1000v-6:
    hostname: 192.168.1.225
    platform: 'ios'
    username: admin
    password: admin
    port: '10004'
    groups:
            - cissh
